services:
  tmr-web_web:
    image: ghcr.io/slatifi/tmr-web_web:latest
    container_name: tmr-web_web
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PUBLIC_SNOMED_BASE_URL=$SNOMED_BASE_URL
      - PUBLIC_API_BASE_URL=$BASE_URL
      - PUBLIC_REQUIRE_EMAIL_VERIFICATION={$REQUIRE_EMAIL_VERIFICATION:-true}

  tmr-web_api:
    image: ghcr.io/slatifi/tmr-web_api:latest
    container_name: tmr-web_api
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-tmr}:${POSTGRES_PASSWORD:-example_password}@tmr-web_db:5432/${POSTGRES_DB:-tmrdb}
      - BETTER_AUTH_URL=$BASE_URL
      - TRUSTED_ORIGINS=$BASE_URL
    # Only uncomment if you want to use a precomputed transitive closure db (see scripts/transitiveclosure)
    # volumes:
    #   - ./path/to/snomed.db:/usr/src/app/snomed.db

  proxy:
    image: caddy:latest
    container_name: tmr-web_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - tmr-web_web
      - tmr-web_api
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  db:
    image: postgres:latest
    container_name: tmr-web_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tmr}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example_password}
      POSTGRES_DB: ${POSTGRES_DB:-tmrdb}
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
  caddy_data:
  caddy_config:
