services:
  db:
    image: postgres:latest
    container_name: tmrw_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-example_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example_password}
      POSTGRES_DB: ${POSTGRES_DB:-tmrwdb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
