name: Web CI

on:
  push:
    brnanches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/web_ci.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web_ci.yml"

jobs:
  web-ci:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.0-noble
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Create .env file
        run: | 
          cat >.env <<EOL
          PUBLIC_API_BASE_URL=http://localhost:3000
          PUBLIC_SNOMED_BASE_URL=http://localhost:3000
          EOL

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared-types package
        run: pnpm --filter @repo/shared-types build

      - name: Type check
        run: pnpm run check-types

      - name: Lint code
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm test
