name: Web CI

on:
  push:
    brnanches:
      - main
    paths:
      - "apps/web/**"
      - ".github/workflows/web_ci.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web_ci.yml"

jobs:
  web-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run check-types

      - name: Lint code
        run: pnpm run lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run unit tests
        run: pnpm test
